import { supabase, boot, esc, money, toast, appUrl } from "./supabase.js";
const {user,profile,role}=await boot("Admin Dashboard","Admin");if(role!=="admin"){document.querySelector(".main").innerHTML=`<div class="card section empty"><h2>Access Denied</h2><p>You do not have administrator access.</p><a class="btn primary" href="${appUrl("dashboard.html")}">Return to Dashboard</a></div>`;throw new Error("Not admin")}
const main=document.querySelector(".main");
main.insertAdjacentHTML("beforeend",`<div class="grid stats" id="stats"></div><div class="card section" style="margin-top:16px"><div class="section-head"><h2>Users</h2><input id="search" placeholder="Search users…" style="max-width:300px"></div><div id="users"></div></div>`);
async function load(){const {data,error}=await supabase.from("admin_user_overview").select("*").order("created_at",{ascending:false});if(error){toast(error.message,true);return}const rows=data||[];const totalRev=rows.reduce((s,x)=>s+Number(x.total_revenue||0),0);stats.innerHTML=`<div class="card stat"><div class="label">Total Users</div><div class="value">${rows.length}</div></div><div class="card stat"><div class="label">Active Users</div><div class="value">${rows.filter(x=>x.account_status==="active").length}</div></div><div class="card stat"><div class="label">Total Invoices</div><div class="value">${rows.reduce((s,x)=>s+Number(x.total_invoices||0),0)}</div></div><div class="card stat"><div class="label">Total Revenue</div><div class="value">${money(totalRev)}</div></div><div class="card stat"><div class="label">Paid Invoices</div><div class="value">${rows.reduce((s,x)=>s+Number(x.paid_invoices||0),0)}</div></div><div class="card stat"><div class="label">Pending Revenue</div><div class="value">${money(rows.reduce((s,x)=>s+Number(x.pending_revenue||0),0))}</div></div>`;
render(rows)}
function render(rows){const q=search.value.trim().toLowerCase();const r=rows.filter(x=>!q||[x.full_name,x.business_name,x.email].some(v=>String(v||"").toLowerCase().includes(q)));users.innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>User</th><th>Business</th><th>Email</th><th>Registered</th><th>Status</th><th>Invoices</th><th>Revenue</th><th>Actions</th></tr></thead><tbody>${r.map(x=>`<tr><td>${esc(x.full_name||"")}</td><td>${esc(x.business_name||"")}</td><td>${esc(x.email||"")}</td><td>${new Date(x.created_at).toLocaleDateString()}</td><td><span class="badge ${x.account_status==="active"?"paid":"disabled"}">${x.account_status}</span></td><td>${x.total_invoices||0}</td><td>${money(x.total_revenue||0)}</td><td class="actions"><button class="btn ghost mini view" data-id="${x.id}">View</button><button class="btn secondary mini toggle" data-id="${x.id}" data-status="${x.account_status}">${x.account_status==="active"?"Disable":"Enable"}</button><button class="btn danger mini del" data-id="${x.id}">Delete</button></td></tr>`).join("")||`<tr><td colspan="8" class="empty">No users found.</td></tr>`}</tbody></table></div>`;
document.querySelectorAll(".view").forEach(b=>b.onclick=()=>location.href=`../admin/index.html?user=${b.dataset.id}`);document.querySelectorAll(".toggle").forEach(b=>b.onclick=async()=>{const next=b.dataset.status==="active"?"disabled":"active";const {error}=await supabase.rpc("admin_set_account_status",{target_user_id:b.dataset.id,new_status:next});if(error)toast(error.message,true);else load()});document.querySelectorAll(".del").forEach(b=>b.onclick=()=>deleteUser(b.dataset.id))}
async function deleteUser(id){if(!confirm("Delete this user and their application data?"))return;const {data,error}=await supabase.functions.invoke("admin-delete-user",{body:{user_id:id}});if(error||data?.error){toast(error?.message||data?.error||"Delete failed",true);return}toast("User deleted.");load()}
search.oninput=()=>load();load();
