import { supabase, boot, esc, toast, debounce } from "./supabase.js";
await boot("Customers","Customers");const app=document.getElementById("app");let editing=null;
app.insertAdjacentHTML("beforeend",`<div class="card section"><div class="section-head"><h2>Customers</h2><button id="add" class="btn primary">＋ Add Customer</button></div><div class="toolbar"><input id="search" placeholder="Search customers…"></div><div id="list"></div></div>
<div id="modal" class="modal hidden"><div class="modal-card"><div class="section-head"><h2 id="mtitle">Add Customer</h2><button id="close" class="btn ghost">×</button></div><form id="form" class="form-grid"><label>Name<input id="name" required></label><label>Company<input id="company"></label><label>Email<input id="email" type="email"></label><label>Phone<input id="phone"></label><label class="full-col">Address<textarea id="address"></textarea></label><div class="full-col"><button class="btn primary">Save</button></div></form></div></div>`);
const modal=document.getElementById("modal");
function open(x=null){editing=x;document.getElementById("mtitle").textContent=x?"Edit Customer":"Add Customer";["name","company","email","phone","address"].forEach(k=>document.getElementById(k).value=x?.[k]||"");modal.classList.remove("hidden")}
document.getElementById("add").onclick=()=>open();document.getElementById("close").onclick=()=>modal.classList.add("hidden");
async function load(){const q=document.getElementById("search").value.trim();let req=supabase.from("customers").select("*").order("name");if(q)req=req.or(`name.ilike.%${q}%,company_name.ilike.%${q}%,email.ilike.%${q}%`);const {data,error}=await req;if(error)return toast(error.message,true);document.getElementById("list").innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Company</th><th>Email</th><th>Phone</th><th>Actions</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.company_name||"")}</td><td>${esc(x.email||"")}</td><td>${esc(x.phone||"")}</td><td class="actions"><button class="btn ghost mini edit" data-id="${x.id}">Edit</button><button class="btn danger mini del" data-id="${x.id}">Delete</button><a class="btn secondary mini" href="invoice-editor.html?customer=${x.id}">Invoice</a></td></tr>`).join("")||`<tr><td colspan="5" class="empty">No customers yet — add a customer.</td></tr>`}</tbody></table></div>`;
document.querySelectorAll(".edit").forEach(b=>b.onclick=async()=>{const {data}=await supabase.from("customers").select("*").eq("id",b.dataset.id).single();open(data)});document.querySelectorAll(".del").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this customer?"))return;const {error}=await supabase.from("customers").delete().eq("id",b.dataset.id);if(error)toast(error.message,true);else load()})}
document.getElementById("form").onsubmit=async e=>{e.preventDefault();const payload={name:name.value.trim(),company_name:company.value.trim()||null,email:email.value.trim()||null,phone:phone.value.trim()||null,address:address.value.trim()||null};let r=editing?await supabase.from("customers").update(payload).eq("id",editing.id):await supabase.from("customers").insert(payload);if(r.error)toast(r.error.message,true);else{modal.classList.add("hidden");load()}};document.getElementById("search").oninput=debounce(load,300);load();
