import { supabase, boot, esc, money, toast } from "./supabase.js";
const {user,profile}=await boot("Create Invoice","Create Invoice");const app=document.getElementById("app");const params=new URLSearchParams(location.search);const editId=params.get("id");const customerParam=params.get("customer");let products=[],customers=[],editingInvoice=null;
app.insertAdjacentHTML("beforeend",`<form id="invoiceForm"><div class="grid two"><div class="card section"><div class="section-head"><h2>Invoice Information</h2><span id="mode" class="muted"></span></div><div class="form-grid">
<label>Customer<select id="customer" required><option value="">Select customer</option></select></label><label>Invoice Number<input id="invoiceNumber" readonly></label>
<label>Invoice Date<input id="invoiceDate" type="date" required></label><label>Due Date<input id="dueDate" type="date" required></label>
<label>Currency<select id="currency"><option>LKR</option><option>USD</option><option>EUR</option><option>GBP</option><option>INR</option><option>AUD</option><option>CAD</option></select></label>
<label>Status<select id="status"><option>draft</option><option selected>pending</option><option>paid</option><option>overdue</option><option>cancelled</option></select></label>
<label>Discount %<input id="discount" type="number" min="0" max="100" step="0.01" value="0"></label><label>Payment Terms<input id="paymentTerms" value="Due on receipt"></label>
<label class="full-col">Notes<textarea id="notes" placeholder="Optional notes"></textarea></label></div></div>
<div class="card section"><h2>Business</h2><p><b>${esc(profile.business_name||profile.full_name)}</b></p><p class="muted">${esc(profile.address||"")}<br>${esc(profile.phone||"")} ${esc(profile.email||"")}</p></div></div>
<div class="card section" style="margin-top:16px"><div class="section-head"><h2>Items</h2><button type="button" class="btn secondary" id="addItem">＋ Add Item</button></div><div class="invoice-items"><table class="items-table"><thead><tr><th>Product</th><th>Description</th><th>Qty</th><th>Unit Price</th><th>Discount %</th><th>Tax %</th><th>Total</th><th></th></tr></thead><tbody id="items"></tbody></table></div>
<div class="invoice-summary" style="margin-top:18px"><div class="summary-row"><span>Subtotal</span><b id="subtotal">0</b></div><div class="summary-row"><span>Discount</span><b id="discountTotal">0</b></div><div class="summary-row"><span>Tax</span><b id="taxTotal">0</b></div><div class="summary-row summary-total"><span>Total</span><b id="grandTotal">0</b></div></div>
<div style="display:flex;justify-content:flex-end;gap:8px;margin-top:20px"><a class="btn ghost" href="invoices.html">Cancel</a><button class="btn primary" id="saveBtn">Save Invoice</button></div></div></form>`);
const itemBody=document.getElementById("items");
function addItem(item={}){const tr=document.createElement("tr");tr.innerHTML=`<td><select class="prod"><option value="">Custom</option>${products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select></td><td><input class="desc" value="${esc(item.description||"")}"></td><td><input class="qty" type="number" min="0.01" step="0.01" value="${item.quantity??1}"></td><td><input class="price" type="number" min="0" step="0.01" value="${item.unit_price??0}"></td><td><input class="disc" type="number" min="0" max="100" step="0.01" value="${item.discount??0}"></td><td><input class="tax" type="number" min="0" step="0.01" value="${item.tax_rate??0}"></td><td class="line-total">0</td><td><button type="button" class="btn danger mini remove">×</button></td>`;itemBody.appendChild(tr);if(item.product_id)tr.querySelector(".prod").value=item.product_id;tr.querySelector(".prod").onchange=()=>{const p=products.find(x=>x.id===tr.querySelector(".prod").value);if(p){tr.querySelector(".desc").value=p.description||"";tr.querySelector(".price").value=p.price;tr.querySelector(".tax").value=p.tax_rate}};tr.querySelector(".remove").onclick=()=>{tr.remove();calc()};tr.querySelectorAll("input").forEach(x=>x.oninput=calc);calc()}
function calc(){let sub=0,tax=0;itemBody.querySelectorAll("tr").forEach(tr=>{const q=+tr.querySelector(".qty").value||0,p=+tr.querySelector(".price").value||0,d=+tr.querySelector(".disc").value||0,t=+tr.querySelector(".tax").value||0;const gross=q*p,disc=gross*d/100,net=gross-disc,ta=net*t/100;sub+=net;tax+=ta;tr.querySelector(".line-total").textContent=money(net+ta,currency.value)});const d= sub*(+discount.value||0)/100,total=sub-d+tax;subtotal.textContent=money(sub,currency.value);discountTotal.textContent=money(d,currency.value);taxTotal.textContent=money(tax,currency.value);grandTotal.textContent=money(total,currency.value)}
async function init(){const [c,p]=await Promise.all([supabase.from("customers").select("*").order("name"),supabase.from("products").select("*").order("name")]);if(c.error||p.error){toast((c.error||p.error).message,true);return}customers=c.data||[];products=p.data||[];customer.innerHTML=`<option value="">Select customer</option>${customers.map(x=>`<option value="${x.id}">${esc(x.name)}${x.company_name?" — "+esc(x.company_name):""}</option>`).join("")}`;document.getElementById("addItem").onclick=()=>addItem();discount.oninput=calc;currency.onchange=calc;
const today=new Date().toISOString().slice(0,10);invoiceDate.value=today;dueDate.value=today;const {data:settings}=await supabase.from("settings").select("*").single();currency.value=settings?.default_currency||"LKR";paymentTerms.value=settings?.default_payment_terms||"Due on receipt";
if(editId){mode.textContent="Editing";const {data,error}=await supabase.from("invoices").select("*,invoice_items(*)").eq("id",editId).single();if(error){toast(error.message,true);return}editingInvoice=data;invoiceNumber.value=data.invoice_number;invoiceDate.value=data.invoice_date;dueDate.value=data.due_date;currency.value=data.currency;status.value=data.status;discount.value=data.discount?((Number(data.discount)/(Number(data.subtotal)||1))*100).toFixed(2):0;notes.value=data.notes||"";paymentTerms.value=data.payment_terms||"";customer.value=data.customer_id;data.invoice_items.forEach(addItem);calc()}else{const n=settings?.next_invoice_number||1,prefix=settings?.invoice_prefix||"INV";invoiceNumber.value=`${prefix}-${String(n).padStart(4,"0")}`;if(customerParam)customer.value=customerParam;addItem()}}
invoiceForm.onsubmit=async e=>{e.preventDefault();saveBtn.disabled=true;try{if(!customer.value)throw new Error("Select a customer.");const rows=[...itemBody.querySelectorAll("tr")];if(!rows.length)throw new Error("Add at least one item.");let subtotalV=0,taxV=0;const items=rows.map(tr=>{const q=+tr.querySelector(".qty").value,p=+tr.querySelector(".price").value,d=+tr.querySelector(".disc").value||0,t=+tr.querySelector(".tax").value||0;const gross=q*p,disc=gross*d/100,net=gross-disc,ta=net*t/100;subtotalV+=net;taxV+=ta;return{product_id:tr.querySelector(".prod").value||null,description:tr.querySelector(".desc").value.trim(),quantity:q,unit_price:p,discount:d,tax_rate:t,tax_amount:ta,total:net+ta}});const discountV=subtotalV*(+discount.value||0)/100,totalV=subtotalV-discountV+taxV;const payload={customer_id:customer.value,invoice_number:invoiceNumber.value,invoice_date:invoiceDate.value,due_date:dueDate.value,currency:currency.value,status:status.value,subtotal:subtotalV,discount:discountV,tax:taxV,total:totalV,notes:notes.value.trim()||null,payment_terms:paymentTerms.value.trim()||null};let invoiceId=editId;if(editId){const r=await supabase.from("invoices").update(payload).eq("id",editId);if(r.error)throw r.error;const d=await supabase.from("invoice_items").delete().eq("invoice_id",editId);if(d.error)throw d.error}else{const r=await supabase.from("invoices").insert(payload).select("id").single();if(r.error)throw r.error;invoiceId=r.data.id;const s=await supabase.from("settings").update({next_invoice_number:(settings?.next_invoice_number||1)+1}).eq("user_id",user.id);if(s.error)throw s.error}
const ir=await supabase.from("invoice_items").insert(items.map(x=>({...x,invoice_id:invoiceId})));if(ir.error){if(!editId)await supabase.from("invoices").delete().eq("id",invoiceId);throw ir.error}
toast("Invoice saved.");location.href=`invoice-detail.html?id=${invoiceId}`}catch(err){toast(err.message||"Could not save invoice.",true)}finally{saveBtn.disabled=false}};init();
