import { supabase, boot, esc, money, toast } from "./supabase.js";
const {profile}=await boot("Invoice","Invoices");const app=document.getElementById("app");const id=new URLSearchParams(location.search).get("id");
async function load(){if(!id){location.href="invoices.html";return}const {data:i,error}=await supabase.from("invoices").select("*,customers(*),invoice_items(*)").eq("id",id).single();if(error){toast(error.message,true);return}
app.insertAdjacentHTML("beforeend",`<div class="no-print" style="display:flex;justify-content:flex-end;gap:8px;margin-bottom:12px"><a class="btn ghost" href="invoices.html">Back</a><a class="btn secondary" href="invoice-editor.html?id=${i.id}">Edit</a><button class="btn secondary" id="duplicate">Duplicate</button><button class="btn secondary" id="print">Print</button><button class="btn primary" id="pdf">Download PDF</button><button class="btn danger" id="delete">Delete</button></div>
<div class="invoice-paper" id="paper"><div class="invoice-head"><div>${profile.logo_url?`<img class="invoice-logo" src="${profile.logo_url}" alt="Logo">`:""}<h2>${esc(profile.business_name||profile.full_name)}</h2><div class="muted">${esc(profile.address||"")}<br>${esc(profile.phone||"")}<br>${esc(profile.email||"")} ${esc(profile.website||"")}</div></div><div class="invoice-meta"><p class="invoice-title">INVOICE</p><b>${esc(i.invoice_number)}</b><div>Date: ${i.invoice_date}</div><div>Due: ${i.due_date}</div><div style="margin-top:8px"><span class="badge ${i.status}">${i.status}</span></div></div></div>
<div class="invoice-parties"><div><h4>BILL TO</h4><b>${esc(i.customers?.name||"")}</b><div>${esc(i.customers?.company_name||"")}</div><div>${esc(i.customers?.address||"")}</div><div>${esc(i.customers?.email||"")}</div><div>${esc(i.customers?.phone||"")}</div></div><div><h4>PAYMENT TERMS</h4><div>${esc(i.payment_terms||"")}</div></div></div>
<table class="invoice-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th>Tax</th><th>Total</th></tr></thead><tbody>${i.invoice_items.map(x=>`<tr><td>${esc(x.description||"")}</td><td>${x.quantity}</td><td>${money(x.unit_price,i.currency)}</td><td>${x.tax_rate}%</td><td>${money(x.total,i.currency)}</td></tr>`).join("")}</tbody></table>
<div class="invoice-summary" style="margin-top:25px"><div class="summary-row"><span>Subtotal</span><b>${money(i.subtotal,i.currency)}</b></div><div class="summary-row"><span>Discount</span><b>${money(i.discount,i.currency)}</b></div><div class="summary-row"><span>Tax</span><b>${money(i.tax,i.currency)}</b></div><div class="summary-row summary-total"><span>Grand Total</span><b>${money(i.total,i.currency)}</b></div></div>
${i.notes?`<div style="margin-top:35px"><h4>Notes</h4><p>${esc(i.notes)}</p></div>`:""}</div>`);
print.onclick=()=>window.print();delete.onclick=async()=>{if(!confirm("Delete this invoice?"))return;const {error}=await supabase.from("invoices").delete().eq("id",id);if(error)toast(error.message,true);else location.href="invoices.html"};
duplicate.onclick=async()=>{const copy={...i};delete copy.id;delete copy.created_at;delete copy.updated_at;delete copy.customers;delete copy.invoice_items;copy.invoice_number=`${i.invoice_number}-COPY`;copy.status="draft";const r=await supabase.from("invoices").insert(copy).select("id").single();if(r.error)toast(r.error.message,true);else{const ir=await supabase.from("invoice_items").insert(i.invoice_items.map(x=>{const y={...x};delete y.id;delete y.created_at;y.invoice_id=r.data.id;return y}));if(ir.error)toast(ir.error.message,true);else location.href=`invoice-detail.html?id=${r.data.id}`}};
pdf.onclick=async()=>{try{const {jsPDF}=window.jspdf;const doc=new jsPDF("p","mm","a4");const paper=document.getElementById("paper");await doc.html(paper,{margin:10,autoPaging:"text",width:190,windowWidth:900});doc.save(`${i.invoice_number}.pdf`)}catch(e){toast("PDF generation failed.",true)}};
}
load();
