import { supabase, boot, esc, toast, setTheme } from "./supabase.js";
const {user,profile}=await boot("Settings","Settings");const app=document.getElementById("app");
const {data:s}=await supabase.from("settings").select("*").single();
app.insertAdjacentHTML("beforeend",`<div class="grid two"><div class="card section"><div class="section-head"><h2>Business Settings</h2></div><form id="form" class="form-grid">
<label>Business Name<input id="business_name" value="${esc(profile.business_name||"")}"></label><label>Email<input id="email" type="email" value="${esc(profile.email||"")}"></label><label>Phone<input id="phone" value="${esc(profile.phone||"")}"></label><label>Website<input id="website" value="${esc(profile.website||"")}"></label><label>Tax Number<input id="tax_number" value="${esc(profile.tax_number||"")}"></label><label>Logo<input id="logo" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="full-col">Address<textarea id="address">${esc(profile.address||"")}</textarea></label>
<label>Invoice Prefix<input id="prefix" value="${esc(s?.invoice_prefix||"INV")}"></label><label>Next Invoice Number<input id="nextNumber" type="number" min="1" value="${s?.next_invoice_number||1}"></label>
<label>Default Currency<select id="currency">${["LKR","USD","EUR","GBP","INR","AUD","CAD"].map(x=>`<option ${x===(s?.default_currency||"LKR")?"selected":""}>${x}</option>`).join("")}</select></label>
<label>Default Tax Rate %<input id="taxRate" type="number" min="0" step="0.01" value="${s?.default_tax_rate||0}"></label>
<label>Default Payment Terms<input id="terms" value="${esc(s?.default_payment_terms||"Due on receipt")}"></label>
<label>Theme<select id="theme"><option value="light">Light</option><option value="dark">Dark</option></select></label>
<div class="full-col"><button class="btn primary">Save Settings</button></div></form></div><div class="card section"><h2>Logo</h2><p class="muted">Use a small PNG/JPG/WebP logo. Storage access is restricted to your own folder.</p>${profile.logo_url?`<img src="${profile.logo_url}" style="max-width:220px;max-height:120px;object-fit:contain">`:"<div class='empty'>No logo uploaded.</div>"}</div></div>`);
theme.value=localStorage.getItem("theme")||"light";theme.onchange=()=>setTheme(theme.value);
form.onsubmit=async e=>{e.preventDefault();try{let logo_url=profile.logo_url||null;const file=logo.files[0];if(file){if(file.size>6*1024*1024)throw new Error("Logo must be 6MB or smaller.");const path=`${user.id}/logo-${Date.now()}.${file.name.split(".").pop()}`;const up=await supabase.storage.from("business-logos").upload(path,file,{upsert:true,contentType:file.type});if(up.error)throw up.error;const signed=await supabase.storage.from("business-logos").createSignedUrl(path,31536000);if(signed.error)throw signed.error;logo_url=signed.data.signedUrl}
const p={business_name:business_name.value.trim(),email:email.value.trim(),phone:phone.value.trim()||null,address:address.value.trim()||null,website:website.value.trim()||null,tax_number:tax_number.value.trim()||null,logo_url};const pr=await supabase.from("profiles").update(p).eq("id",user.id);if(pr.error)throw pr.error;const sp={invoice_prefix:prefix.value.trim()||"INV",next_invoice_number:+nextNumber.value||1,default_currency:currency.value,default_tax_rate:+taxRate.value||0,default_payment_terms:terms.value.trim()||"Due on receipt"};const sr=await supabase.from("settings").update(sp).eq("user_id",user.id);if(sr.error)throw sr.error;toast("Settings saved.");theme.value=localStorage.getItem("theme")||theme.value;}catch(err){toast(err.message||"Could not save settings.",true)}};
